server:
  servlet:
    session:
      timeout: 86400

spring:
  profiles:
    include: dev
  jpa:
    show-sql: true
    open-in-view: false #default : true이기에 수정해야 함.
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        highlight_sql: true
        format_sql: true
        default_batch_fetch_size: 100

  sql:
    init:
      mode: always

